name:                fcc-backend-api-practices
version:             0.1.0.0
github:              "modotte/fcc-backend-api-practices"
license:             BSD3
author:              "Modotte"
copyright:           "2022 Modotte"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/modotte/fcc-backend-api-practices#readme>
default-extensions: NoImplicitPrelude, OverloadedStrings
dependencies:
- base >= 4.7 && < 5
- relude
- text
- bytestring
- aeson
- time
- network
- iproute
- scotty
- wai
- wai-extra
- uuid
- random
- data-default-class

library:
  source-dirs: src

executables:
  fcc-backend-api-practices-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

    dependencies:
    - fcc-backend-api-practices

tests:
  fcc-backend-api-practices-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcc-backend-api-practices
    - hspec
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - quickcheck-instances
